#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openvpn
Version  : 2.5.1
Release  : 12
URL      : https://github.com/OpenVPN/openvpn/archive/v2.5.1/openvpn-2.5.1.tar.gz
Source0  : https://github.com/OpenVPN/openvpn/archive/v2.5.1/openvpn-2.5.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: openvpn-bin = %{version}-%{release}
Requires: openvpn-config = %{version}-%{release}
Requires: openvpn-lib = %{version}-%{release}
Requires: openvpn-man = %{version}-%{release}
Requires: openvpn-services = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : docutils
BuildRequires : iproute2
BuildRequires : lz4-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(cmocka)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libpkcs11-helper-1)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(lzo2)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(p11-kit-1)
BuildRequires : pkgconfig(systemd)
BuildRequires : sed

%description
OpenVPN -- A Secure tunneling daemon
you can redistribute it and/or modify
it under the terms of the GNU General Public License version 2
as published by the Free Software Foundation.

%package bin
Summary: bin components for the openvpn package.
Group: Binaries
Requires: openvpn-config = %{version}-%{release}
Requires: openvpn-services = %{version}-%{release}

%description bin
bin components for the openvpn package.


%package config
Summary: config components for the openvpn package.
Group: Default

%description config
config components for the openvpn package.


%package dev
Summary: dev components for the openvpn package.
Group: Development
Requires: openvpn-lib = %{version}-%{release}
Requires: openvpn-bin = %{version}-%{release}
Provides: openvpn-devel = %{version}-%{release}
Requires: openvpn = %{version}-%{release}

%description dev
dev components for the openvpn package.


%package doc
Summary: doc components for the openvpn package.
Group: Documentation
Requires: openvpn-man = %{version}-%{release}

%description doc
doc components for the openvpn package.


%package lib
Summary: lib components for the openvpn package.
Group: Libraries

%description lib
lib components for the openvpn package.


%package man
Summary: man components for the openvpn package.
Group: Default

%description man
man components for the openvpn package.


%package services
Summary: services components for the openvpn package.
Group: Systemd services

%description services
services components for the openvpn package.


%prep
%setup -q -n openvpn-2.5.1
cd %{_builddir}/openvpn-2.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614363589
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%reconfigure --disable-static --enable-iproute2 \
--enable-systemd \
SYSTEMD_UNIT_DIR=/usr/lib/systemd/system \
TMPFILES_DIR=/usr/lib/tmpfiles.d
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1614363589
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/openvpn

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/openvpn.conf

%files dev
%defattr(-,root,root,-)
/usr/include/openvpn-msg.h
/usr/include/openvpn-plugin.h

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/openvpn/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so
/usr/lib64/openvpn/plugins/openvpn-plugin-down-root.so

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/openvpn.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/openvpn-client@.service
/usr/lib/systemd/system/openvpn-server@.service
